---
abstract: 'Dist::Zilla - add badges to github README.md'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-GitHubREADME-Badge
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: 0
resources:
  bugtracker: https://github.com/fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge/issues
  homepage: https://github.com/fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge
  repository: https://github.com/fayland/perl-Dist-Zilla-Plugin-GitHubREADME-Badge.git
version: 0.03
